### ISSUE TITLE
error occurs when I try to compile

### ISSUE THREAD

**Issue by hamidb80** [flaviut/nim-by-example#88] opened 2021-02-05 07:46 UTC
Hey. I'm not a Ruby expert, But I wanted to add some styles to the project and contribute.
I just clone the repo and tried to compile that (using `bundle exec nanoc`), but the`nanoc` said:

```
Captain! We’ve been hit!

Nanoc::Int::Errors::NoMatchingCompilationRuleFound: No compilation rules were found for the “/assets/img/logo_bw.png” item.

  0. /var/lib/gems/2.7.0/gems/nanoc-4.9.9/lib/nanoc/rule_dsl/action_provider.rb:32:in `rep_names_for'
  1. /var/lib/gems/2.7.0/gems/nanoc-4.9.9/lib/nanoc/base/services/item_rep_builder.rb:16:in `block in run'
  2. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:1316:in `each'
  3. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:1316:in `traverse_depth_first'
  4. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:1317:in `block in traverse_depth_first'
  5. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:1317:in `each'
  6. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:1317:in `traverse_depth_first'
  7. /usr/lib/ruby/vendor_ruby/hamster/vector.rb:431:in `each'
  8. /usr/lib/ruby/2.7.0/forwardable.rb:235:in `each'
  9. /var/lib/gems/2.7.0/gems/nanoc-4.9.9/lib/nanoc/base/services/item_rep_builder.rb:15:in `run'
  ... 27 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
```

I'll be thanful if you could help me.

**Comment by flaviut** [comment] 2021-02-07 01:45
Pull the latest version & try again. Thank you for reporting :)

**Comment by hamidb80** [comment] 2021-02-07 08:09
> Pull the latest version & try again. Thank you for reporting :)

it seems like code highlighting doesn't work in the last version

**Comment by flaviut** [comment] 2021-02-07 16:52
You need [Pygments](https://pygments.org/) installed. You can install it with `pip install --user pygmentize`, just make sure that `$(python3 -m site --user-base)/bin` is on your `PATH` (can you successfully run `which pygmentize`?)

**Comment by hamidb80** [comment] 2021-02-08 07:03
>  (can you successfully run `which pygmentize`?)

I do have that.

Am I doing something wrong? here's what I enter:
```
bundle exec nanoc compile
bundle exec nanoc view
```

the last command just give me some deprecated warnings & a URL to view the the generated website.

**Comment by hamidb80** [comment] 2021-02-08 07:21
>  (can you successfully run `which pygmentize`?)

yes, I do have pygmentize in `/usr/bin/pygmentize`.

Am I doing something wrong? here's what I enter:
```
bundle exec nanoc
bundle exec nanoc view
```

the last command just gives me some deprecated warnings & a URL to view the the generated website.
```
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:243: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:155: warning: The called method `option' is defined here
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:220: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:155: warning: The called method `option' is defined here
Loading site… done
Compiling site…
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/nanoc-4.9.9/lib/nanoc/base/services/compiler_loader.rb:34: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/nanoc-4.9.9/lib/nanoc/base/services/compiler.rb:7: warning: The called method `initialize' is defined here

Site compiled in 0.05s.
-----------------------------------------------------------------------------------------

/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:243: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:155: warning: The called method `option' is defined here
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:220: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/cri-2.15.3/lib/cri/command_dsl.rb:155: warning: The called method `option' is defined here
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/rack-2.0.6/lib/rack/builder.rb:86: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/hamidb80/Documents/programming/nim/nim-by-example/vendor/bundle/ruby/2.7.0/gems/adsf-1.4.1/lib/adsf/rack/index_file_finder.rb:5: warning: The called method `initialize' is defined here
View the site at http://127.0.0.1:3000/
[2021-02-08 10:51:08] INFO  WEBrick 1.6.0
[2021-02-08 10:51:08] INFO  ruby 2.7.0 (2019-12-25) [x86_64-linux-gnu]
[2021-02-08 10:51:08] INFO  WEBrick::HTTPServer#start: pid=21400 port=3000

```

**Comment by flaviut** [comment] 2021-02-09 02:46
I'm not really sure what's wrong there. Perhaps delete the `output/` directory, use `strace -o log bundle exec nanoc`, and then look through log for calls to "pygmentize"? The log file would be pretty big, but just the lines around an occurrence of "pygmentize" would help a bunch in debugging.

**Comment by flaviut** [comment] 2021-02-09 02:47
And the favicon issue in your screenshot--it's been a long time since I've worked on this, I messed up the config. It's unrelated, and it should be fixed in the latest version.

**Comment by hamidb80** [comment] 2021-02-09 04:27
> and then look through log for calls to "pygmentize"?
There is no "pygmentize" in `log` file but there are some "pygment":

```
36814:read(5, "/* pygments-css colorful */\ncode"..., 6447) = 6447

44530:openat(AT_FDCWD, "/usr/lib/ruby/vendor_ruby/rouge/formatters/html_pygments.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 5

44537:openat(AT_FDCWD, "/usr/lib/ruby/vendor_ruby/rouge/formatters/html_pygments.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 5

44550:lstat("/usr/lib/ruby/vendor_ruby/rouge/formatters/html_pygments.rb", {st_mode=S_IFREG|0644, st_size=417, ...}) = 0

44551:stat("/usr/lib/ruby/vendor_ruby/rouge/formatters/html_pygments.rb", {st_mode=S_IFREG|0644, st_size=417, ...}) = 0
```

**Comment by flaviut** [comment] 2021-02-10 16:22
It looks like nanoc is calling out to rouge, another code highlighter. I'm not sure why it's doing this, since the config very clearly says to use pygmentize.

I don't really have time to get into finding the root cause of this but:

- What happens when you run `bundler update` and then try rebuilding? If this is an issue with old versions of stuff, I'm fine with bumping the versions.
- If that doesn't work, you can probably work around this by doing `apt remove ruby-rouge`. You probably have other stuff depending on rouge though, and that'd have to go too.

**Closed** 2021-02-11 05:51 UTC
